# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 20:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DayOfWeek', models.CharField(max_length=20)),
                ('Type', models.CharField(max_length=20)),
                ('StartTime', models.CharField(max_length=5)),
                ('EndTime', models.CharField(max_length=5)),
                ('PlacesCount', models.IntegerField()),
                ('StartDate', models.IntegerField()),
                ('EndDate', models.IntegerField(blank=True)),
                ('Active', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='client',
            name='Name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='Phone',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='Name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='Trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shedule.Trainer'),
        ),
        migrations.RemoveField(
            model_name='class',
            name='Trainer',
        ),
        migrations.DeleteModel(
            name='Class',
        ),
    ]
