# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-24 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shedule', '0004_auto_20160124_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='PlacesCount',
            field=models.IntegerField(blank=True),
        ),
    ]
