# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 17:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shedule', '0005_auto_20160124_0906'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shedule.Client')),
                ('Lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shedule.Lesson')),
            ],
        ),
    ]
